#!/bin/bash
set -euo pipefail

echo "pre-exit hook, running"


pwd
ls

name="test_cleanup"


echo "running cleanup script ./src/cleanaup/$name.sh"

chmod +x ./src/cleanaup/$name.sh

./.buildkite/cleanaup/$name.sh



echo "script called"