#!/bin/bash
set -euo pipefail

echo "pre-exit hook, running"


pwd
ls

name="test_cleanup"

cd src

ls


echo "running cleanup script /src/$name.sh"

chmod +x /src/$name.sh

./src/$name.sh



echo "script called"